version: '3'

services:
  # DBサーバ
  postgres:
    image: postgres:13
    volumes:
      - ./postgres/db-data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always

  # keycloak
  keycloak:
    image: jboss/keycloak:15.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 80:8080
    depends_on:
      - postgres
    restart: always

  # gitea
  gitea:
    image: gitea/gitea:1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=password
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - postgres

  # drone.io
  drone:
    image: drone/drone:2
    ports:
    - "9000:80"
    environment:
    - DRONE_SERVER_HOST=192.168.11.100:9000
    - DRONE_SERVER_PROTO=http
    - DRONE_RPC_SECRET=947745830e98a00deb5378dcd3b5dcd1
    - DRONE_COOKIE_SECRET=e8206356c843d81e05ab6735e7ebf075
    - DRONE_COOKIE_TIMEOUT=720h
    - DRONE_GITEA_CLIENT_ID=fc08a282-072d-4f6f-b0d7-d2497f895ad8
    - DRONE_GITEA_CLIENT_SECRET=kvZL85RaymiKz5Gs3giX81yW4SxTqZcavNxR0239LIzh
    - DRONE_GITEA_SERVER=http://192.168.11.100:3000
    - DRONE_LOGS_DEBUG=true
    - DRONE_CRON_DISABLED=true
    - DRONE_DATABASE_DRIVER=postgres
    - DRONE_DATABASE_DATASOURCE=postgres://postgres:password@postgres:5432/drone?sslmode=disable
    volumes:
    - ./drone/data:/data
    depends_on:
      - postgres

  runner:
    image: drone/drone-runner-docker:1
    environment:
    - DRONE_RPC_HOST=drone
    - DRONE_RPC_PROTO=http
    - DRONE_RPC_SECRET=947745830e98a00deb5378dcd3b5dcd1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  # docker registory
  registry:
    image: registry:2
    volumes:
      - ./registry:/var/lib/registry
    ports:
      - 5000:5000
    restart: always
